### PR TITLE
#17 Added Cocoapods support

### PR DESCRIPTION
**Pull request by agruchala**
#17  Added Cocoapods support by including podfile

### CODE REVIEW

**Comment by agruchala** [comment]
Hi! After merging, please create a new tag, 0.3.3 and make `pod repo push` so it is available, ping me when you are done;)

**Comment by c-villain** [comment]
thx for you contributing!

**Comment by agruchala** [comment]
Remember to do pod repo push and create new tag! :)

**Comment by c-villain** [comment]
@agruchala check this out

**Pull request merged**
